DROP TABLE IF EXISTS authors CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS comments CASCADE;

CREATE TABLE authors(
    id BIGINT generated by default as identity,
    name varchar(255),
    surname varchar(255),
    primary key (id)
);

CREATE TABLE genres(
    id BIGINT generated by default as identity,
    name varchar(255),
    primary key (id)
);

CREATE TABLE books(
    id BIGINT generated by default as identity,
    author_id BIGINT,
    genre_id BIGINT,
    title varchar(255),
    primary key (id),
    FOREIGN KEY (author_id) REFERENCES authors(id),
    FOREIGN KEY (genre_id) REFERENCES genres(id)
);

CREATE TABLE comments(
    id BIGINT generated by default as identity,
    text varchar(255),
    book_id BIGINT,
    primary key (id),
    FOREIGN KEY (book_id) REFERENCES books(id)
);